# Outgoing email settings

production:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.kion.it
    port: 25
    domain: kion.it
    authentication: :login
    user_name: asalicetti@kion.it
    password: 3e4r5t&Y/U(I
  
development:
  delivery_method: :smtp
  smtp_settings:
    address: smtp.kion.it
    port: 25
    domain: kion.it
    authentication: :login
    user_name: asalicetti@kion.it
    password: 3e4r5t&Y/U(I
